catalog/urls.py
from django.urls import path , include
from . import views


app_name = 'catalog'

urlpatterns = [
    path ('' , views.index.as_view(), name = 'index'),
    path ('books/' , views.BookListView.as_view() , name = 'books'),
    path ('books/<int:pk>/' , views.BookDetailView.as_view() , name = 'book-detail'),
    path ('authors/' , views.AuthorlistView.as_view(), name = 'authors'),
]

library/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/' , include('catalog.urls')),
]

urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
urlpatterns += [
    path('accounts/' , include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid 
class Genre (models.Model):
    #Representing book genre

    name = models.CharField(max_length =200 , help_text="Enter a book genre(e. g. science fiction , French Poetry etc.) ")
    
    def __str__(self):
        return self.name


class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author' , on_delete=models.SET_NULL , null =True)
    summary = models.TextField(max_length=1000 , help_text="enter a brief description of the book")
    isbn = models.CharField('ISBN' , max_length = 13 )
    genre = models.ManyToManyField(Genre , help_text = "select a genre for this book")

    def __str__(self) : 
        return self.title

    def get_absolute_url(self):
        return reverse('catalog:book_detail', args = [str(self.id)])

    def display_genre(self):
        """
         Creates a string for the Genre. This is required to display genre in Admin.
        """
        return ', '.join([ genre.name for genre in self.genre.all()[:3] ])

    display_genre.short_description = 'Genre'

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True , default = uuid.uuid4 )
    book = models.ForeignKey('Book' , on_delete=models.SET_NULL , null = True)
    imprint = models.CharField(max_length = 200)
    due_back = models.DateField(null=True , blank = True)

    LOAN_STATUS = (
        ('m' , 'Maintenance'),
        ('o' , 'On loan'),
        ('a' , 'Available'),
        ('r' , 'Reserved'),
    )

    status = models.CharField(max_length = 1 , choices = LOAN_STATUS , blank = True , default = 'm' )

    class Meta :
        ordering = ["due_back"]

    def __str__(self):
        return '%s (%s)' %(self.id , self.book.title)


class Author (models.Model):
    first_name = models.CharField(max_length = 100)
    last_name = models.CharField(max_length = 100)
    date_of_birth = models.DateField(null = True , blank = True)
    date_of_death = models.DateField('Died' , null = True , blank = True)

    def get_absolute_url(self):
        return reverse('catalog:author-detail' , args = [str(self.id)])

    def __str__(self):
        return '%s , %s' % (self.last_name , self.first_name)

catalog/views.py
from django.shortcuts import render
from django.views import generic
from . import models 
from django.views.generic.base import TemplateView

class index(generic.TemplateView):

    template_name ='catalog/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context ['num_books'] = models.Book.objects.all().count()
        context ['num_instances'] = models.BookInstance.objects.all().count()
        context ['num_instances_available'] = models.BookInstance.objects.filter(status__exact='a').count()
        context ['num_author'] = models.Author.objects.all().count()
        return context


class BookListView(generic.ListView):
    model = models.Book
    template_name = 'catalog/Book_list.html'

class BookDetailView(generic.DetailView):
    model = models.Book
    template_name = 'catalog/Book_detail.html'

class AuthorlistView (generic.ListView):

    model = models.Author
    templet_name = 'catalog/author_list.html'
# def index(request) : 

#     num_books = models.Book.objects.all().count()
#     num_instance = models.BookInstance.objects.all().count()
#     num_instances_available =models.BookInstance.objects.filter(status__exact = 'a').count()
#     num_authors = models.Author.objects.count()

#     return render(
#         request , 
#         'catalog/index.html',
#         context = {'num_books' : num_books , 'num_instances' : num_instance , 'num_instaces_available' : num_instances_available , 'num_authors' : num_authors} , 
#         )

catalog/templates/catalog/Book_detail.html
{% extends "catalog/base_generic.html" %}

{% block content %}
  <h1>Title: {{ book.title }}</h1>

  <p><strong>Author:</strong> <a href="">{{ book.author }}</a></p> <!-- author detail link not yet defined -->
  <p><strong>Summary:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p> 
  <p><strong>Language:</strong> {{ book.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in book.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in book.bookinstance_set.all %}
    <hr>
    <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">{{ copy.get_status_display }}</p>
    {% if copy.status != 'a' %}<p><strong>Due to be returned:</strong> {{copy.due_back}}</p>{% endif %}
    <p><strong>Imprint:</strong> {{copy.imprint}}</p>
    <p class="text-muted"><strong>Id:</strong> {{copy.id}}</p>
    {% endfor %}
  </div>
{% endblock %}

catalog/templates/catalog/Book_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ Book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}       
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "catalog/base_generic.html" %}

{% block content %}
    {% for author in author_list %}
        <h2>Author : {{author.last_name}} </h2>
        <p>Author first name : {{author.first_name}} </p>
        <p>date of birth : {{author.date_of_birth}} </p>
        <p>date of death : {{author.date_of_death}} </p>
        <hr>
    {% endfor %}
{% endblock %}

catalog/templates/catalog/index.html
{% extends "catalog/base_generic.html" %}

{% block content %}
<h1>Local Library Home</h1>

  <p>Welcome to <em>LocalLibrary</em>, a very basic Django website </p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Books:</strong> {{ num_books }}</li>
    <li><strong>Copies:</strong> {{ num_instances }}</li>
    <li><strong>Copies available:</strong> {{ num_instances_available }}</li>
    <li><strong>Authors:</strong> {{ num_authors }}</li>
  </ul>

{% endblock %}

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'catalog/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'catalog:index' %}">Home</a></li>
          <li><a href="{% url 'catalog:books' %}">All books</a></li>
          <li><a href="{% url 'catalog:authors'%}">All authors</a></li>
          <li><a href="/admin/">Admin page</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>